[project]
name = "lattice-boltzmann"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.4",
    "tqdm>=4.67.3",
]

# -------------------------------------------------
# --------- pytorch optional dependencies ---------
# install pytorch with e.g. 'uv sync --extra cu128'
# -------------------------------------------------

[project.optional-dependencies]
cu128 = [
  "torch>=2.11.0",
]
cu130 = [
  "torch>=2.11.0",
]

[tool.uv]
conflicts = [
  [
    { extra = "cu128" },
    { extra = "cu130" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", extra = "cu128" },
  { index = "pytorch-cu130", extra = "cu130" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

# -------------------------------------------------
# -------------------------------------------------
# -------------------------------------------------

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "T201",  # print statements
    "PLR0913",  # too many arguments in function call
    "PLR0915",  # too many local variables
]
